### ISSUE TITLE
安装之后lsp里找不到这个模块！

### ISSUE THREAD

**Issue by suaosong** [Xposed-Modules-Repo/com.yuk.fuckmiuithememanager#2]
安装之后在lsp管理器找不到这个模块，会不会是由于我的lSP版本太老？？
![Screenshot_2022-03-13-09-17-32-011_io github lsposed manager](https://user-images.githubusercontent.com/36725964/158040731-411ffcb0-b2a2-4881-a86a-6929269ecd13.jpg)
![Screenshot_2022-03-13-09-17-28-772_io github lsposed manager](https://user-images.githubusercontent.com/36725964/158040732-92c31035-a38b-4ad9-a856-ace161b3d650.jpg)

**Comment by YuKongA** [comment]
是，更新LSPosed版本
